### ISSUE TITLE
isusses 139 jdownloader on raspberpi zero hypriot os

### ISSUE THREAD

**Issue by moussa86** [jaymoulin/jaymoulin.github.io#2]
{
        "Id": "ec7141eab08963d0b12d3c518a601e4bfd0ce4c9bcf2f332f1858acff05e85b6",
        "Created": "2019-01-31T20:41:14.024259674Z",
        "Path": "tini",
        "Args": [
            "--",
            "/opt/JDownloader/daemon.sh"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 139,
            "Error": "",
            "StartedAt": "2019-01-31T21:13:55.832230457Z",
            "FinishedAt": "2019-01-31T21:13:56.805807634Z"
        },
        "Image": "sha256:c9a9856275c004e19622f5badb3618100d1aad609b63f71ce8f241271ec45b2a",
        "ResolvConfPath": "/var/lib/docker/containers/ec7141eab08963d0b12d3c518a601e4bfd0ce4c9bcf2f332f1858acff05e85b6/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ec7141eab08963d0b12d3c518a601e4bfd0ce4c9bcf2f332f1858acff05e85b6/hostname",
        "HostsPath": "/var/lib/docker/containers/ec7141eab08963d0b12d3c518a601e4bfd0ce4c9bcf2f332f1858acff05e85b6/hosts",
        "LogPath": "/var/lib/docker/containers/ec7141eab08963d0b12d3c518a601e4bfd0ce4c9bcf2f332f1858acff05e85b6/ec7141eab08963d0b12d3c518a601e4bfd0ce4c9bcf2f332f1858acff05e85b6-json.log",
        "Name": "/jdownloader",
        "RestartCount": 39,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/root/Downloads:/root/Downloads",
                "/root/jdownloader/cfg:/opt/JDownloader/cfg"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ad62fcf6673b84728615d41b86a61c5accf9c9f0381cf45988deb0bfcd626993-init/diff:/var/lib/docker/overlay2/ea48ef0fae0b7f10d6af8fe3c56ef343080aacd67a110148d641a7bb5a3e22cb/diff:/var/lib/docker/overlay2/5674f282c23e754f0ed82fe7e7a2a233a556d98b831f1a308bd040b2eba7204e/diff:/var/lib/docker/overlay2/496b6788b317846976393194828d96a07bd9f88ec2d3ff489875c6f056cbcba1/diff:/var/lib/docker/overlay2/595da174beaabf03a68816f7e2023b3c81dd90772132b679e898d6c9909b1a5b/diff:/var/lib/docker/overlay2/8ced3058defcc877db6ea5a4238ac4d848a0cd10ad922eaf189539e4b7d9eae3/diff:/var/lib/docker/overlay2/a4029a222c94277e4e1d162c1dc6fa7a615d28e454b53c75575c5c6dd533142b/diff:/var/lib/docker/overlay2/183f2b210aa4a16f2c89070d7ad8c50d182d6d1688c7a766fa3d55730cc9e49f/diff:/var/lib/docker/overlay2/cd7995beddf2d5800f5d40d41ca8d1d1e5a4180e42dbaa6cf1615440955195b4/diff:/var/lib/docker/overlay2/0640dbf0f2b72ebf1d5f5105d9b801fffc98b7fbb0c1b6935fbd41c020c2800e/diff:/var/lib/docker/overlay2/957c62de477cbba46011ab99fb9d92de41590de7a3d56e97e85bc341cd1dcd52/diff:/var/lib/docker/overlay2/8d52c81116ac62c26ee5a5aa91753263d747aa74c8153839b868b0c6920a5ae1/diff:/var/lib/docker/overlay2/867eb6551f821bc750052dafc1ece676f1068ac3e04bf7fe79b934ba69975dcc/diff:/var/lib/docker/overlay2/b529c27391c5034aa70afc643f6fde940e9d9d4db7c1b8da46b1f17b24ff566c/diff:/var/lib/docker/overlay2/24681d6dfe3b74396deff2e8fdb550647ce453d64d4884717e403a58931acea6/diff",
                "MergedDir": "/var/lib/docker/overlay2/ad62fcf6673b84728615d41b86a61c5accf9c9f0381cf45988deb0bfcd626993/merged",
                "UpperDir": "/var/lib/docker/overlay2/ad62fcf6673b84728615d41b86a61c5accf9c9f0381cf45988deb0bfcd626993/diff",
                "WorkDir": "/var/lib/docker/overlay2/ad62fcf6673b84728615d41b86a61c5accf9c9f0381cf45988deb0bfcd626993/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/root/jdownloader/cfg",
                "Destination": "/opt/JDownloader/cfg",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/root/Downloads",
                "Destination": "/root/Downloads",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "ec7141eab089",
            "Domainname": "",
            "User": "0:0",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk/bin",
                "JAVA_VERSION=8",
                "JAVA_UPDATE=73",
                "JAVA_BUILD=02",
                "JAVA_HOME=/opt/jdk",
                "LD_LIBRARY_PATH=/lib;/lib32;/usr/lib",
                "LANG=C.UTF-8",
                "LC_ALL=C.UTF-8"
            ],
            "Cmd": [
                "tini",
                "--",
                "/opt/JDownloader/daemon.sh"
            ],
            "ArgsEscaped": true,
            "Image": "jaymoulin/jdownloader",
            "Volumes": null,
            "WorkingDir": "/opt/JDownloader",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "Description": "This image is used as base image for my explorations of running JAVA/Node applications on a Raspberry Pi 2 cluster.",
                "Version": "0.1",
                "maintainer": "Jay MOULIN <jaymoulin@gmail.com> <https://twitter.com/MoulinJay>",
                "version": "0.6.1-armhf"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "0ed47901869e0f3764f54834d19ceec75d502135b6789be76c1c7df9d96c0af2",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/0ed47901869e",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "53d32f9dc72d2a51bc75156cd5736c796e4052cd0f0f4a5a466d57dceb2fbdc8",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }

**Comment by jaymoulin** [comment]
Wrong repo. You probably mean https://github.com/jaymoulin/docker-jdownloader. This will help you redact your issue with required information
